# Generated by Django 3.2.4 on 2024-07-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flan',
            fields=[
                ('flan_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default=' ')),
                ('image_url', models.URLField(default=' ', unique=True)),
                ('slug', models.SlugField(default=' ', unique=True)),
                ('is_private', models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
