# Generated by Django 3.2.4 on 2024-07-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_flan_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flan',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
