# Generated by Django 3.2.4 on 2024-07-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20240712_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='flan',
            name='image_url',
            field=models.URLField(default=' ', unique=True),
        ),
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(default=' ', unique=True),
        ),
    ]
