# Generated by Django 3.2.4 on 2024-07-13 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20240712_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('contact_form_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_name', models.CharField(max_length=64)),
                ('message', models.TextField(default='Deje un mensaje')),
            ],
        ),
    ]
